data:
  start_date           : "2017-01-01"
  end_date             : "2025-12-31"
  raw_path             : "data/raw"
  processed_path       : "data/processed"
  reports_path         : "model_performance_reports"
  current_model_version: "v2"
tickers:
  nifty_50:
    - "ADANIENT.NS"
    - "ADANIPORTS.NS"
    - "APOLLOHOSP.NS"
    - "ASIANPAINT.NS"
    - "AXISBANK.NS"
    - "BAJAJ-AUTO.NS"
    - "BAJFINANCE.NS"
    - "BAJAJFINSV.NS"
    - "BHARTIARTL.NS"
    - "BPCL.NS"
    - "BRITANNIA.NS"
    - "CIPLA.NS"
    - "COALINDIA.NS"
    - "DIVISLAB.NS"
    - "DRREDDY.NS"
    - "EICHERMOT.NS"
    - "GRASIM.NS"
    - "HCLTECH.NS"
    - "HDFCBANK.NS"
    - "HDFCLIFE.NS"
    - "HEROMOTOCO.NS"
    - "HINDALCO.NS"
    - "HINDUNILVR.NS"
    - "ICICIBANK.NS"
    - "INDUSINDBK.NS"
    - "INFY.NS"
    - "ITC.NS"
    - "JSWSTEEL.NS"
    - "KOTAKBANK.NS"
    - "LT.NS"
    - "LTIM.NS"
    - "M&M.NS"
    - "MARUTI.NS"
    - "NESTLEIND.NS"
    - "NTPC.NS"
    - "ONGC.NS"
    - "POWERGRID.NS"
    - "RELIANCE.NS"
    - "SBILIFE.NS"
    - "SBIN.NS"
    - "SHRIRAMFIN.NS"
    - "SUNPHARMA.NS"
    - "TATACONSUM.NS"
    - "TMPV.NS"
    - "TATASTEEL.NS"
    - "TCS.NS"
    - "TECHM.NS"
    - "TITAN.NS"
    - "ULTRACEMCO.NS"
    - "WIPRO.NS"

  nifty_next_50:
    - "ABB.NS"
    - "ACC.NS"
    - "ADANIPOWER.NS"
    - "AMBUJACEM.NS"
    - "AUROPHARMA.NS"
    - "BANKBARODA.NS"
    - "BEL.NS"
    - "BHEL.NS"
    - "BOSCHLTD.NS"
    - "CANBK.NS"
    - "CHOLAFIN.NS"
    - "COLPAL.NS"
    - "CONCOR.NS"
    - "CUMMINSIND.NS"
    - "DABUR.NS"
    - "DLF.NS"
    - "GAIL.NS"
    - "GODREJCP.NS"
    - "HAL.NS"
    - "HAVELLS.NS"
    - "ICICIGI.NS"
    - "ICICIPRULI.NS"
    - "IGL.NS"
    - "INDIGO.NS"
    - "INDUSTOWER.NS"
    - "IOC.NS"
    - "IRCTC.NS"
    - "JINDALSTEL.NS"
    - "LICI.NS"
    - "MARICO.NS"
    - "MOTHERSON.NS"
    - "NAUKRI.NS"
    - "PIDILITIND.NS"
    - "PFC.NS"
    - "PNB.NS"
    - "RECLTD.NS"
    - "SAIL.NS"
    - "SBICARD.NS"
    - "SIEMENS.NS"
    - "SRF.NS"
    - "TATACHEM.NS"
    - "TATACOMM.NS"
    - "TATAPOWER.NS"
    - "TORNTPHARM.NS"
    - "TVSMOTOR.NS"
    - "UNITDSPR.NS"
    - "UPL.NS"
    - "VEDL.NS"
    - "ZEEL.NS"
    - "ZYDUSLIFE.NS"
  historical_constituents:
    - "YESBANK.NS"
    - "RBLBANK.NS"
    - "SAMMAANCAP.NS"
    - "IDEA.NS"
    - "ZEEL.NS"
    - "BANDHANBNK.NS"
    - "ACC.NS"
    - "AMBUJACEM.NS"
    - "AUROPHARMA.NS"
    - "BANKBARODA.NS"
    - "BHEL.NS"
    - "BOSCHLTD.NS"
    - "CANBK.NS"
    - "DLF.NS"
    - "GAIL.NS"
    - "GLENMARK.NS"
    - "HINDPETRO.NS"
    - "INDIGO.NS"
    - "JINDALSTEL.NS"
    - "LUPIN.NS"
    - "UNITDSPR.NS"
    - "NMDC.NS"
    - "PETRONET.NS"
    - "PNB.NS"
    - "SAIL.NS"
    - "SIEMENS.NS"
    - "TATACHEM.NS"
    - "TATAPOWER.NS"
    - "VEDL.NS"
    - "ZYDUSLIFE.NS"
indices:
  - "^NSEI"
  - "^NSMIDCP"